running ['zsync', '-o', '/Users/pierre/Downloads/renpy-6.99.13-sdk/update/editra-mac.update.new', '-k', '/Users/pierre/Downloads/renpy-6.99.13-sdk/update/editra-mac.zsync', '-i', '/Users/pierre/Downloads/renpy-6.99.13-sdk/update/editra-mac.update', 'http://update.renpy.org/6.99.13/renpy-6.99.13-editra-mac.zsync']
running ['zsync', '-o', '/Users/pierre/Downloads/renpy-6.99.13-sdk/update/editra-mac.update.new', 'http://update.renpy.org/6.99.13/renpy-6.99.13-editra-mac.zsync']
Traceback (most recent call last):
  File "renpy/common/00updater.rpy", line 329, in run
    self.update()
  File "renpy/common/00updater.rpy", line 436, in update
    self.download(i, standalone=True)
  File "renpy/common/00updater.rpy", line 918, in download
    cwd=renpy.fsencode(self.updatedir))
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 710, in __init__
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 1335, in _execute_child
OSError: [Errno 2] No such file or directory
